# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dd3f85086f8e2c4c6775cde90d1c493d81a0d9fd68fbb3604c51c09c5fc617cb27617be63e747217336ef57a060cfdb317a0c40c4956f8005ccd956f253f4a8

test:
  secret_key_base: 4d31d35df2d330acc93ed87b9ba2d1a7804c329a165d20cdc75433b0d06638bbe0305317bfd67b8313e1d7fa6a45f2423598e91d75b9cf7a63950da3048c91ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
